-- Apr 2, 2014 11:07:26 AM VET
-- LVE Withholding
CREATE TABLE LVE_CashTax (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Cash_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_Tax_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTaxIncluded CHAR(1) CHECK (IsTaxIncluded IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, TaxAmt NUMERIC NOT NULL, TaxBaseAmt NUMERIC NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_CashTax_Key PRIMARY KEY (C_Cash_ID, C_Tax_ID))
;

-- Oct 20, 2014 5:45:59 PM VET
-- LVE ADempiere
CREATE TABLE I_Product_Category (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, I_ErrorMsg VARCHAR(2000) DEFAULT NULL , I_IsImported CHAR(1) DEFAULT NULL CHECK (I_IsImported IN ('Y','N')), I_Product_Category_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) DEFAULT NULL , CONSTRAINT I_Product_Category_Key PRIMARY KEY (I_Product_Category_ID))
;



-- Dec 16, 2014 5:03:58 PM VET
-- LVE ADempiere
CREATE TABLE LVE_ProductReport (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_ProductReport_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_ProductReport_Key PRIMARY KEY (LVE_ProductReport_ID))
;

-- Dec 16, 2014 5:04:05 PM VET
-- LVE ADempiere
CREATE TABLE LVE_ProductReportLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LVE_ProductReport_ID NUMERIC(10) NOT NULL, LVE_ProductReportLine_ID NUMERIC(10) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , PrintName VARCHAR(60) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_ProductReportLine_Key PRIMARY KEY (LVE_ProductReportLine_ID))
;


-- Jan 13, 2015 10:03:00 AM VET
-- FTA
CREATE TABLE LVE_WH_UserDocSequence (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Sequence_ID NUMERIC(10) DEFAULT NULL , AD_User_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, ControlNoSequence_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsPrintSetControlNo CHAR(1) DEFAULT 'N' CHECK (IsPrintSetControlNo IN ('Y','N')), Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_WH_UserDocSequence_Key PRIMARY KEY (AD_User_ID, C_DocType_ID))
;

