--	References C_UOM
ALTER TABLE M_InventoryLine ADD CONSTRAINT FK_M_Requisition_C_UOM FOREIGN KEY (C_Uom_ID)
	REFERENCES C_UOM(C_Uom_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;

ALTER TABLE LVE_ProductReportLine ADD CONSTRAINT LVE_ProductReportLine_ProductReport FOREIGN KEY (LVE_ProductReport_ID)
REFERENCES LVE_ProductReport(LVE_ProductReport_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE LVE_ProductReportLine ADD CONSTRAINT LVE_ProductReportLine_ProductCategory FOREIGN KEY (M_Product_Category_ID)
REFERENCES M_Product_Category(M_Product_Category_ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE LVE_ProductReportLine ADD CONSTRAINT LVE_ProductReportLine_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product(M_Product_ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;