ALTER TABLE LVE_WarehouseProduct ADD CONSTRAINT FK_LVE_WarehouseProduct_AD_Table FOREIGN KEY (AD_Table_ID)
	REFERENCES AD_Table(AD_Table_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
	
ALTER TABLE LVE_WarehouseProductLine ADD CONSTRAINT FK_LVE_WarehouseProductLine_LVE_WarehouseProduct_ID FOREIGN KEY (LVE_WarehouseProduct_ID)
	REFERENCES LVE_WarehouseProduct(LVE_WarehouseProduct_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;

ALTER TABLE LVE_WarehouseProductLine ADD CONSTRAINT FK_LVE_WarehouseProductLine_M_Warehouse_ID FOREIGN KEY (M_Warehouse_ID)
	REFERENCES M_Warehouse(M_Warehouse_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;
	
ALTER TABLE LVE_WarehouseProductLine ADD CONSTRAINT FK_LVE_WarehouseProductLine_M_Product_ID FOREIGN KEY (M_Product_ID)
	REFERENCES M_Product(M_Product_ID) 
	ON UPDATE CASCADE 
	ON DELETE RESTRICT;